name: Run tests on different Python 🐍 versions and operating systems.

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        python-version: [3.8, 3.11]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install pypa/build
        run: >-
          python -m pip install build --user
      - name: Run pip install
        run: pip install -r requirements.txt
      - name: Run contract as tests with Specmatic Python
        run: coverage run --branch -m pytest test -v -s --junitxml contract-test-reports/TEST-junit-jupiter.xml
      - name: Publish contract test report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/contract-test-reports/TEST-*.xml'
      - name: Generate coverage report
        run: coverage html -d coverage-report
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage-report
